name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: API (Python 3.11)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install API deps (dev)
        run: |
          python -m pip install -U pip wheel
          pip install -e "apps/api[dev]"
          pip install pytest
      - name: Run tests (SQLite, no Redis)
        env:
          USE_SQLITE: "1"
          DISABLE_REDIS: "1"
        working-directory: apps/api
        run: python -m pytest -q

  web:
    name: Web (Node 20 + pnpm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: apps/web/pnpm-lock.yaml
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install
        working-directory: apps/web
        run: pnpm install --frozen-lockfile=false
      - name: Build
        working-directory: apps/web
        run: pnpm build
