name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-and-health:
    runs-on: ubuntu-latest
    steps:
      - run: echo OK
