name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-and-health:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Detect Python
        id: detect_py
        run: |
          if ls -1 **/*.py 2>/dev/null | grep -q . || [ -f requirements.txt ] || [ -f pyproject.toml ]; then echo "is_python=true" >> $GITHUB_OUTPUT; else echo "is_python=false" >> $GITHUB_OUTPUT; fi

      - name: Setup Python
        if: steps.detect_py.outputs.is_python == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python deps (best effort)
        if: steps.detect_py.outputs.is_python == 'true'
        run: |
          python -m pip install -U pip wheel
          if [ -f pyproject.toml ]; then pip install -e ".[dev]" || true; pip install -e . || true; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          python - <<'PY'
          try:
              import fastapi  # noqa
          except Exception:
              import os
              os.system('pip install fastapi pydantic')
          PY
          pip install pytest || true

      - name: Run smoke test only (SQLite/no-Redis)
        if: steps.detect_py.outputs.is_python == 'true'
        env:
          USE_SQLITE: '1'
          DISABLE_REDIS: '1'
          PYTHONPATH: '.'
        run: |
          pytest -q apps/api/tests/test_smoke_ci.py

      - name: Detect Web (Next.js)
        id: detect_web
        run: |
          if [ -f apps/web/package.json ]; then echo "has_web=true" >> $GITHUB_OUTPUT; else echo "has_web=false" >> $GITHUB_OUTPUT; fi

      - name: Setup Node (web)
        if: steps.detect_web.outputs.has_web == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Build Next.js web
        if: steps.detect_web.outputs.has_web == 'true'
        run: |
          corepack enable || true
          pnpm --version || npm i -g pnpm
          pnpm -C apps/web install
          pnpm -C apps/web build
